# Generated by Django 3.2.4 on 2021-07-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='kilo',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(max_length=200),
        ),
    ]
